### ISSUE TITLE
Getting AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by stephanbuettig** [ashaherb/Wiley-Downloader#2]
Hi,

thank you very much for your work. I tried your script via Peppermint OS, but unfortunately I get the following error.

`python scraper.py https://onlinelibrary.wiley.com/doi/book/10.1002/9783527678488
Traceback (most recent call last):
  File "scraper.py", line 22, in <module>
    title_text = ''.join(title.findAll(text=True))
AttributeError: 'NoneType' object has no attribute 'findAll'
`

Do you have a solution?

Sincerly

Stephan

**Comment by ashaherb** [comment]
Hi,

Can you use the scrapper on Book pages instead like this one here: http://onlinelibrary.wiley.com/book/10.1002/9781118033104

The goal of this scrapper is to merge the PDF chapter files on an open access book, So the page has to have links for PDF chapter files

**Comment by Imtiaz08** [comment]
Hi, thank you so much for your work I am using the code to download a book that is divided into 34 chapters from wiley online library. At first I got some errors which I figured out by changing different things such as urllib2 to urllib3 and pyPDF3 etc however, I am still getting this error 

Traceback (most recent call last):
  File "c:\Users\IMTIAZ NABI\AppData\Local\Programs\Python\Python39\scraper.py", line 17, in <module>
    url = sys.argv[1]
IndexError: list index out of range

Kindly help me if you can I need this book for my research. Thank you once again
